before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: pSI4N+sgp21mrSP1nbmQLiV+jfevpDWkxZ6FJSr33UyJWbBo0eoeYwUItn9OYXftV0HElKK47LvOh7GRbnWWQEe6pw5XTi8sqX3NHAY4R6lIrZZYmrzvRmpYP+dYe4ZPhYoa+dO3JvUA3OKgt7a3PfhA0eKBoAvP3H0qyfuXsELIcqfksGyL5yp7B6TrwvyoVnQZGHSFHnvQnxzguVFDZIMcZz4cprelC7dr3YIgODmsrjOWU2xxTLIAlpyGZ8eAwnzp6qV2zqLoU3dtx37f80cD9a7WaLZmpo2k3fVA1L+divcvqbTql6WibGLtxzRuvM5x0PB1R4xaY2hLRc1mSep/578ovTVQU63dZiYGYlyY/ZQR/8/T1R9ds2Oqgj0FVjKn25GW+XO4O/h3i3//2rdN3VdQarx3oa4wpttrl6ZvVTUd2OiCcHSOkNbVpByToLCm7WD24gX2Iz4kObucoQauC2ialUSM4Ozhd2Nl+rx/TMJkAqtVQZba9lyDRenpSJkPzk4JrVALvVHzjWKbyThJ+bKi0FLKwDVDuwrs887EBTruVRqTKMBsrpAN52RxoznQCimnmfUf/P5MT2owsfle+pLjKBVNTV4OlMkBAlxiEokYVfq4azSAPXIdA/cBX+Rr/yxJRvwrW5hnNWthSg7Jc6mYlT09L83uesHkVuM= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    # - 6
    - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
